version: '3.8'

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
    hostname: localhost
    ports:
      - "8080:8080"
    networks:
      - chat_myNetTest
networks:
  default:
    external:
      name: chat_myNetTest