version: '3.8'

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
    hostname: localhost
    ports:
      - "8080:8080"
    networks:
      - myNetTest
networks:
  myNetTest:
    driver: bridge